### PR TITLE
Adding twilio api

### PR DESCRIPTION
**Pull request by jeremystoll**
I have made a new phone number, confirmed my own number, installed Twilio Gemfile, installed cUrl in an attempt to troubleshoot the connection. I am trying to use the command line to send a test SMS, before moving it into a method, but I get Authentication error.

### CODE REVIEW

**Comment by halfghaninne** [comment]
Hm. When you are trying things out in command line are you creating a new Twilio Client using your credentials?

**Comment by jeremystoll** [comment]
Yes- Like this:

`
@client.account.messages.create({
  :from => '+14028502532', 
  :to => '+14022133739', 
  :body => 'Hey User! Twilio says Hello!', 
  :media_url => 'http://farm2.static.flickr.com/1075/1404618563_3ed9a44a3a.jpg', 
})
`

**Comment by halfghaninne** [comment]
If you are trying that out in command line, entirely, what is `@client`? I see you set it up pretty nicely in your config/twillio.rb file but I would assume that you don't have access to that if you are just trying things out in command line.

Let me know if I'm misunderstanding something.

**Comment by jeremystoll** [comment]
I am running this before, in cmd line:

`@client = Twilio::REST::Client.new account_sid, auth_token` 

Should I just be setting this up as a method, and test that instead?
Also, is the config/twilio.rb file set up correctly, and in the right place? I am not sure that the gem can see it there (and if it can, then how?). Sorry, ALL of the questions.

**Pull request merged**
