### PR TITLE
redirect devise pages

### PR DESCRIPTION
**Pull request by bethanyhaubert**

### CODE REVIEW

**Comment by bethanyhaubert** [comment]
What I'm trying to do is add a working sign out button on my homepage but despite using the path listed on the error page, it's not working. I've tried the path as both
`<a href="/users/sign_out/(.:format)">Log out</a>
`and 
`<a href="/users/sign_out">Log out</a>`

https://www.dropbox.com/s/zv1812c3qb1j5zf/Screenshot%202016-03-23%2011.52.52.png?dl=0

**Comment by sumeetjain** [comment]
Can you try this?

`<%= link_to("Sign Out", "/users/sign_out", method: "delete") %>`

**Comment by bethanyhaubert** [comment]
thanks, that worked.

**Comment by sumeetjain** [comment]
:+1: Other how-tos are here: https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template

**Comment by bethanyhaubert** [comment]
So now i want to do some redirects:

after user logs in redirect to /dashboard
after new user is created redirect to /onboard

should i use that command ` run rails generate devise:controllers users`?

**Comment by bethanyhaubert** [comment]
re: customizing devise controllers

i ran the generate controller command. now i'm not sure where to do those redirects mentioned in my previous comment.

**Comment by sumeetjain** [comment]
I'm not sure you'll need to generate anything for that. Can you check this page: https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in

And see if that's more helpful?

**Comment by bethanyhaubert** [comment]
how can i uninstall the controllers?

**Comment by halfghaninne** [comment]
Jumping in here for Sumeet. I'm not sure what you're trying to accomplish but I _think_ you can just delete any controller or controller action that you do not want.

**Comment by bethanyhaubert** [comment]
devise created an entire folder with multiple files. not sure what else it added

**Comment by halfghaninne** [comment]
When you ran the generate controller command, did you get feedback in the command line regarding what files were created? (I imagine it was just the users folder in your controllers folder) What happens if you delete those files?

**Comment by bethanyhaubert** [comment]
sumeet has a thing about deleting folders manually, but i did it anyway.  i think that'll do it. thank you!

**Pull request merged**
