### PR TITLE
view current business clients & fix dropdown

### PR DESCRIPTION
**Pull request by bethanyhaubert**

### CODE REVIEW

**Comment by sumeetjain** [comment]
Did I not `push` the work I did with y'all? It looks like I didn't, because your branch (prior to your latest commit - https://github.com/omahacodeschool/sms-crm/pull/79/commits/5f813e3712845568d9967efdee66f6888d376ca0) didn't have the model changes.

Now that you've made them, is it possible to give a specific "X should be working but instead Y error is coming up" explanation? If not, it's okay–I'll just need to meet with you to figure things out.

**Comment by bethanyhaubert** [comment]
i'm not sure if i made the model changes correctly and i didn't make any changes to the db schema because i don't remember that initial command that you need to put in the command line

**Comment by sumeetjain** [comment]
My bad. I didn't push. Get rid of your last commit with `git reset --hard HEAD~1`.

Then switch back to master and `pull`. Then switch back to your feature branch and `git merge master`. Resolve any conflicts, if there are any; then run `bundle exec rake db:migrate`. Report back in like 2 minutes.

**Comment by bethanyhaubert** [comment]
thanks, that worked

**Pull request closed without merging**
