### PR TITLE
change_current_client

### PR DESCRIPTION
**Pull request by bethanyhaubert**

### CODE REVIEW

**Comment by bethanyhaubert** [comment]
I want to change the client who's displayed on the dashboard when you select a different client from a dropdown menu on the dashboard. i'm tired and can't. i need help. i don't want to have to pass the client_id param through the dashboard url, but i'm going to have to, arent' i?

**Comment by sumeetjain** [comment]
I'm afraid you will need to do exactly that. Because progressive enhancement prevents us from jumping straight to JavaScript.

**Comment by sumeetjain** [comment]
In effect, the dashboard becomes a view for managing a _single_ client--for now.

**Comment by bethanyhaubert** [comment]
:dash:

**Comment by bethanyhaubert** [comment]
i want to pass in a default value for my client_id in the dashboard url when no client has been selected, but i need help

**Comment by sumeetjain** [comment]
Can you push your code, so I can see what you have? This should be a quick reply from me, once you do that.

**Comment by sumeetjain** [comment]
Just added code to show you how you might have approached it. Please study those commits, and let me know if you have questions. :airplane:

**Comment by bethanyhaubert** [comment]
what do i do to get them on my version? just 'git pull' ?

**Comment by sumeetjain** [comment]
Yup.

**Comment by bethanyhaubert** [comment]
what about the paths in my client_controller? do i need to change those?

**Comment by sumeetjain** [comment]
No.

Redirecting and Rendering are different.

Redirecting means "start a new 'get' request to the following URL".

Rendering means "find the view located at _____ and return that view's HTML."

**Comment by bethanyhaubert** [comment]
thank you

**Pull request merged**
